travis:
  secure:
    BINSTAR_TOKEN: SgXyp6iz7tOEqdFJqML8AoTOg52y6sJCUMm2ONOzEl03OWsBGNA2ibwO233IkEmDPXjlYb4ueJDGiMsnerLx4Erl5j7p/kjm2DtOHgiHwSka8oKUERTJm/dvZtoz8UxuIV9piqshVJ6yKHRATjYkZcKoVsyJkBsUN+hlskuq0rXIsPbD2p6tu2xwI7SBDAr2ffmwGejDZqrdBAgqoQxgQR5BkZcpW19z2PVG9XN7hZtICvAvHr8qKIMm21ST7Wh3Ja+FQgRuKuBJQRYQUxzI3H1vNAc0nUhqJ2YTk6/znVXMEslNogzU3cgSivLemlg2VYW267wU3xUhBSACMR2ZC3hLVRo4jWlb88IrJ7BezpVJNjC4jKnGCEDnTcGIk0wQV9EUW20rorN3D5jQCtGBe63jfjHEWAsnZhyV/27WBWWmRApoJ8mE1bRIeTYch6Pn1fDEehzBBNgKkhhLQ47P0dNgyHrMZnXoyr+XtMmO24iQ55IdVWatNe2Yiw1rYtQl/jIpT7IJ1qxkVraeMuf5BFz5RXka7U8FiT1zxeBZWS6Tp7f4OuPZrMHvUtfzPlONB5T9RUHrWxmhkjhHhi7Ps1gBZVshUhzfCAQR4rXKZBm3wkAcKCnjq/mLme3mhV5+D0bx2n5XcC2Pxrj/6zQhEBDjcr9UePLXzREBhbhR5Wk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
